### PR TITLE
Updates to Synology Driver

### LINKED ISSUE #175: Synology StorageClass Parameters
Hello, I just started trying out this project using the `synology-iscsi` driver and it works really well so far.

However I feel that the configuration is currently a little inconvenient in that you have to configure the LUN and Target options globally. I think these options would go really well in a `StorageClass`. So instead of having
```yaml
…
driver: synology-iscsi
iscsi:
  lunTemplate:
    type: BLUN
  targetTemplate:
    max_sessions: 0
```
you could instead do something like this:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-blun
…
parameters:
  fsType: ext4
  lunType: BLUN
  targetMaxSessions: 0
```

This way you could easily create multiple storage classes for different LUN types without requiring multiple CSI instances. Similarly one could leverage the `secrets` of the `StorageClass` resource to implement CHAP authentication per `StorageClass` (or even per LUN by using the templating features of the `StorageClass` secrets).

I'd be interested in creating a PR for this feature. Would something like this have a chance of being merged?

### LINKED ISSUE #176: Cannot Create Snapshots on Synology
Hello, I am currently testing the `synology-iscsi` driver and I noticed that snapshots weren't created. During debugging I found that the reason for this issue is that the `SYNO.Core.Storage.iSCSILUN/load_snapshot` API does not exist (returns code 103, documented [here](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/SurveillanceStation/All/enu/Surveillance_Station_Web_API.pdf) on page 25). Instead the API `SYNO.Core.ISCSI.LUN/list_snapshot` could be used. I have successfully tested this and can make a PR (possibly together with a PR for #175) but before doing so I have two questions:

- Did the `load_snapshot` API exist previously and do we need to be keep compatibility for this API? `list_snapshot` uses the UUID instead of the ID of the LUN. The driver gets this value from the snapshot ID which means that any existing snapshots will be using the LUN ID and would need to convert it to a UUID when the snapshot is deleted. New Snapshots should probably store the LUN UUID directly. If this is a bug and the `load_snapshot` API did not exist (or backwards compatibility is not required) we could just refactor the snapshots to use UUIDs instead.
- I noticed that a lot of API calls use `JSON.stringify` on values resulting in *double quoting*. As an example:
  https://github.com/democratic-csi/democratic-csi/blob/19197f9515da57f569c670d14fefb1bfd4e43460/src/driver/controller-synology/http/index.js#L487
  The logs show the corresponding request parameters as `"src_lun_uuid":"\"952f031c-c0d1-455e-8b96-68ce5d4d174d\""`. Is there any particular reason for this? From my testing it seems that it isn't required (but it doesn't seem to do any harm either).

### PR DESCRIPTION
**Pull request by codello**
This PR includes several updates for the Synology driver:

1. **Support for DSM 7**: In DSM 7 the `load_snapshot` API has been removed causing issues with snapshot creation. This PR migrates the relevant method to use `list_snapshot` instead which is available in DSM 6 and DSM 7. This fixes #176 
2. **Improved error handling**: If the Synology API returned an error (e.g. due to a misconfigured driver) it currently causes the driver to crash or at least to emit very confusing error messages (the main culprit for this behavior was a behavior of the `httpClient` raising `responses` instead of exceptions). This PR improves this behavior giving more helpful error messages to cluster admins.
3. **Support for `StorageClass`es**: Although `StorageClass`es were supported previously it was not possible to configure different kinds of volumes through the `StorageClass` API. This PR adds support for all known volume configuration options via the `StorageClass` API (including CHAP authentication). The previous behavior of configuring volumes through the global driver options is retained, but `StorageClass` options take precedence if specified. This fixes #175 
4. **Support for `VolumeSnapshotClass`es**: Similarly to the `StorageClass` API this PR adds support for the `VolumeSnapshotClass` API, exposing all GUI parameters. Again the global driver options are still supported but `VolumeSnapshotClass` take precedence.
5. **Documentation**: This PR removes the `lunTemplate`, `targetTemplate` and `lunSnapshotTemplate` sections from the global driver config example. Instead this PR adds documentation for the configuration via `StorageClass` and `VolumeSnapshotClass` to encourage users to use these APIs instead.

I have successfully tested these changes on a DS1520+ running DSM 7.0.1-42218 Update 3 using a Btrfs volume.

### CODE REVIEW

**Comment by travisghansen** [comment]
Wow! Thanks for the contribution. I haven't had a chance to review it in-depth but I'm generally OK with the changes (assuming they are all still compatible with 6.x).

The one major thing I think needs to remain is the template options (especially the `volume` attribute needs to remain constant for the deployment (I have long-term reasons for this). So, in order to facilitate the original desire (assuming messing with `volume` wasn't a primary objective) my thought is this:

- allow a single param that is a json encoded template (ie: params of `lunTemplate`, `lunSnapshotTemplate` and `targetTemplate`)
- the params are parsed and merged with the `Object.assign()` calls just after the values coming from the yaml and before the hard-coded bits

```
# old
          data = Object.assign({}, driver.options.iscsi.lunTemplate, {
            name: iscsiName,
            location: driver.options.synology.volume,
            size: capacity_bytes,
          });

# new (obviously need to be more defensive, but you get the idea)
          data = Object.assign({}, driver.options.iscsi.lunTemplate, JSON.parse(call.request.parameters.lunTemplate) ,{
            name: iscsiName,
            location: driver.options.synology.volume,
            size: capacity_bytes,
          });
```

If its helpful for testing I can probably punch a hole into firewall for testing against 6.x. You can hit me up on the k8s slack/discord/whatever to discuss details if it's of interest.

**Comment by codello** [comment]
> assuming they are all still compatible with 6.x

All changes should still be compatible but I have only tested DSM 7.

> The one major thing I think needs to remain is the template options (especially the volume attribute needs to remain constant for the deployment (I have long-term reasons for this)

Ah right, I forgot to mention that I also added the `volume` to the `StorageClass` and defaulted the volume to `/volume1` (As most people seem to stick to this default). The default can then be overridden by the global config and by individual `StorageClass`es. Is it necessary that the volume can only be configured globally? I think having the possibility to select a different volume for a `StorageClass` is very useful as it allows to e.g. selectively create volumes on SSDs or hard disks. If only a single volume is used people can still use the global option.

> allow a single param that is a json encoded template

Is there a particular reason you prefer a json (or maybe yaml) encoded template over the more specific options? This was indeed my first approach too but the configuration is arguably less intuitive or *pretty*. Compare
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-chap
parameters:
  fsType: ext4
  lunTemplate: |
    type: BLUN
    dev_attribs:
    - dev_attrib: can_snapshot
      enable: 1
secrets:
  ...
```
to
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-chap
parameters:
  fsType: ext4
  lunType: BLUN
  allowSnapshots: true
secrets:
  …
```

My thoughts/reasons to go with the second approach were mainly:
- Nesting yaml inside a yaml string always feels inelegant.
- It is a little unclear how to handle CHAP credentials. Passing the credentials via `parameters.targetTemplate` would be possible but would expose sensitive data. Passing credentials via secrets is imo the better approach but this gives room to ambiguous situations where both the secret and the template contain different credentials.
- We do not require users to know or reverse-engineer all the `dev_attribs`. Instead they can use the documented `StorageClass` options and let `democratic-csi` handle the Synology API. This also makes the attributes a lot more readable. `spaceReclamation` is a lot clearer than `emulate_tpu`.
- Driver specific options allow for more helpful validation. I already implemented some checks for this (e.g. enabling snapshots on a thick-provisioned volume). The errors returned by the Synology API are not always as helpful. This also opens the possibility of validating `StorageClass` resources through an admission webhook (as `StorageClass` parameters cannot be modified). Of course this could also be implemented with a `lunTemplate` but if we are not basically treating the template as an opaque object for the Synology API I don't see any advantage…

The one downside I can think of is of course that future changes in the Synology API would require an updated implementation in `democratic-csi`. If that's a concern maybe we could support both approaches simultaneously:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-chap
parameters:
  fsType: ext4
  lunType: BLUN
  allowSnapshots: true
  lunTemplate:
    dev_attribs:
    - dev_attrib: some_new_attrib
      enabled: 1
secrets:
  …
```
This could easily be implemented by using `Object.assign` as suggested by you and then updating the resulting `data` object with the specific, known values (such as `lunType` and `allowSnapshots` in this example).

Reading your comment again, maybe I misunderstood and this was your suggestion all along?

**Comment by codello** [comment]
I did a quick testing session on (Virtual)DSM 6.2.4 right now and everything seems to work fine as far as I can tell. I was able to create/delete volumes and snapshots.

I also added the following defaults for the `httpConnection`. This shouldn't impact existing configurations but I think as default values these make sense:
```yaml
httpConnection:
  protocol: https
  port: 5001,
  allowInsecure: false,
  session: democratic-csi
```

**Comment by travisghansen** [comment]
Thanks for all the detailed info and quality work!

Predominantly my reasoning behind leaving `volume` static per-deployment are:

- it's consistent with how all the other drivers operate
- it facilitates implementing `ListVolumes` and friends in the future

Regarding yaml vs json I don't really care. Since yaml is a superset to json we can just use the yaml parser and it will load no matter what is the value.

Does you example with nested structured values even work? The csi spec calls for those to be key/value pairs so I'm unclear how k8s handles that (or if it even allows it...I don't think it does). I'm relatively confident the values must be strings: https://kubernetes.io/docs/concepts/storage/storage-classes/#parameters

**Comment by travisghansen** [comment]
Those defaults don't match a default install (for me anyway). I also would be quite leery about running `https` with cert validation occurring by default as I'm guessing the vast majority of installs using https are running with self-signed certs.

**Comment by codello** [comment]
> Predominantly my reasoning behind leaving volume static per-deployment are: […]

Ah ok, I understand. I think `ListVolumes` could still be implemented by using the `SYNO.Core.Storage.Volume/list` API but I get the point of keeping consistency with the other drivers. I have removed the volume from the `StorageClass` but I have kept the default value of `/volume1`.

> Those defaults don't match a default install (for me anyway)

You are probably right. I was thinking about a situation where `httpConnection` is not specified (which would probably cause the driver to crash) or is empty (defaulting everything to `undefined`). I was thinking that defaulting to secure connections was preferable but you are right that that may only make things more difficult when using self-signed certs. I removed these defaults again.

> Does you example with nested structured values even work?

You are right, the API does not allow nested structures (which is quite unfortunate imo). My example uses a fancy YAML-syntax for multiline strings. So the following two are equivalent. Note the vertical bar `|` that starts the multiline string value:
```yaml
lunTemplate: |
  type: BLUN
  dev_attribs:
  - dev_attrib: can_snapshot
    enable: 1

lunTemplate: "type: BLUN\ndev_attribs:\n- dev_attrib: can_snapshot\n  enable: 1"
```

I have added support for `lunTemplate`, `targetTemplate` on the `StorageClass` and `lunSnapshotTemplate` on the `VolumeSnapshotClass`.

**Comment by travisghansen** [comment]
Awesome! Give me a little time to review more thoroughly and we’ll get it merged!

My windows support is nearly complete which will give me more time to review this.

If you want to go crazy you could run the csi-sanity test suite against it locally to ensure everything passes against both 6.x and 7.x

**Comment by travisghansen** [comment]
OK this looks good, my 2 requests are:

1. revert the changes to the examples allowing templates/etc to be set in the config as before
1. My preference is to not use all the custom parameters and just leave the entirely of that logic in the templates

In the code if we still want to do validation on the parameters before sending the request (I generally avoid this honestly as I never know how things will change over time) then we should validate using strictly the `data` object (where the templates have already been merged) using the 'raw' property names instead of the more user-friendly names.

Let's point this branch to `next` instead of `master` (there may be some conflicts) and if we get everything merged in then I can do some local testing on 6.x and get in the next release `v1.7.0`

**Comment by travisghansen** [comment]
FYI, I managed to get `DSM 7.1-42661` up and running for development/ci,

**Comment by codello** [comment]
> My preference is to not use all the custom parameters and just leave the entirely of that logic in the templates.
All right. I personally prefer to have the custom parameters but in the end it doesn't make that much of a difference. I did implement a special merging behavior for the `dev_attribs` that makes it possible to provide defaults in the global configuration that can be selectively overridden by the `StorageClass`.

I think I'm gonna remove the validation in this case. My original motivation was that the Synology API allows some strange combinations of parameters (e.g. enabling snapshots on a thick provisioned volume). The UI then gets confused a little, indicating that snapshots are possible (but giving an error when actually trying to create a snapshot). However given the lack of proper documentation it is probably better to leave this up to the user.

I did try running `csi-sanity` but I encountered two (possibly related) problems:
- The shebang of the `democratic-csi` caused problems. I had to remove the `${NODE_OPTIONS_CSI_1}` otherwise the server would not start.
- I am running macOS and I'm not currently able to mount iSCSI volumes which makes it difficult to run the test suite.

**Comment by travisghansen** [comment]
What's the intent of these dev_attributes functions? Are you wishing for an additive merged?

**Comment by codello** [comment]
That's the idea, yes. This way the global options could be seen as the defaults that get overridden by the `StorageClass`.
The `dev_attributes` functions achieve this by converting an array of the form `[{"dev_attrib": "can_snapshot", "enable": 1}]` to an object of the form `{can_snapshot: 1}` and back. The object forms can then be merged.

**Comment by travisghansen** [comment]
OK, I've made several changes (https://github.com/democratic-csi/democratic-csi/commit/9026d5e0d643440ecfa0ad6ee1161023be436e56):

- `description` is now a handlebars template
- `description` can be set using `lunTemplate` from the fs config, storage class parameter, or storage class secrets
- I've done away with the additive merge (for now), we may add this back in some shape or form in the future
- I've removed the special handling of the chap config
- related to the above point, you can now create a `targetTemplate` value on the appropriate secret (same as the storage class parameters)

The merging of the templates has the following preference:

- secrets are highest priority
- storage class
- fs config.yaml

Would be great to test everything out and this point and update the docs accordingly.

I've added both DSM6 and DSM7 now to ci (although it looks like the node version there doesn't like the `foo?.bar` syntax so I'll clean that up in a moment).

**Comment by travisghansen** [comment]
Images tagged `next` should have all the most recent changes.

**Comment by codello** [comment]
Sorry for the late reply. I am currently testing the `next` images and so far everything is working well. If I discover any issues I will report back and open a new issue or PR.

**Comment by travisghansen** [comment]
Thanks for taking a look! I’m getting closer and closer to the next release. Windows support is pretty well in place from a code perspective so now I’m just building all the ci tooling for tests and adding windows images to the multiarch images etc. Some of these tasks I’m ignorant on so may take me a bit but I am getting closer.

**Pull request merged**
