### PR TITLE
detachedSnapshotsDatasetParetName option warning

### PR DESCRIPTION
**Pull request by fenio**
warning about removing / commenting out detachedSnapshotsDatasetParentName option

### CODE REVIEW

**Comment by fenio** [comment]
I see not too much interest in merging these changes so I presume that including my guide in official doc won't be accepted too but just in case you want another guide that you can reference to then I think mine is ready for review.
https://github.com/fenio/k8s-truenas

**Comment by fenio** [comment]
If you want separate MR/PR for that I'm happy to do so.

**Comment by travisghansen** [comment]
Hey! Contributions are greatly appreciated. Life has just been very hectic for many months :(

Feel free to include your guide in the readme as part of this PR and I’ll get to it.

**Comment by fenio** [comment]
I've just updated PR with link to my guide.
I also fixed one typo I spotted in the meantime.

**Comment by fenio** [comment]
Given that this is just docs update I hope you'll find some time to tackle this. But of course take your time. I know how it works as I'm Debian project member and sometimes I simply have no time to deal with such minor updates.

**Comment by travisghansen** [comment]
lgtm!

**Comment by fenio** [comment]
Thanks!

**Pull request merged**
