### PR TITLE
Fix obsolete API version.

### PR DESCRIPTION
**Pull request by christian-schlichtherle**

### CODE REVIEW

**Comment by christian-schlichtherle** [comment]
The old version "2" produces the error code 103. I'm running DSM 7.0.1.

**Comment by travisghansen** [comment]
Is version 6 available in the latest 6.x of dsm?

**Comment by christian-schlichtherle** [comment]
The linked document says it’s up to date with DSM 7. Valid ranges are 3 to 7, where 6 is recommended.

**Comment by travisghansen** [comment]
Perhaps. With the change does everything else work as expected?

I’ll do some more research on dsm6 to see if version 6 works.

**Comment by christian-schlichtherle** [comment]
I could not test that because the code base is incompatible with my Node version and the GitHub actions require a lot of setup.

**Comment by travisghansen** [comment]
Sorry didn’t get a notice this was changed! I’ll merge and new images will build.

**Comment by travisghansen** [comment]
Ok use image tag `next` and make sure to set the pull policy to always and give it a whirl.

**Comment by travisghansen** [comment]
Did you ever try this out?

**Comment by christian-schlichtherle** [comment]
Unfortunately not because I have switched to the driver provided by Synology.

**Comment by travisghansen** [comment]
Sounds good.

**Pull request merged**
